blank_issues_enabled: false
contact_links:
  - name: Contributing!
    url: https://github.com/catppuccin/mouadhbendjedidi/the/new?category=port-requests
    about: wanna know How to contribute? Click me!